services:
  - type: web
    name: invoice-processor-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --worker-class=gthread --workers=2 --threads=4 --worker-tmp-dir /dev/shm
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: main.py
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: PORT
        value: 10000
      - key: UPLOAD_FOLDER
        value: /opt/render/project/src/uploads
      - key: PROCESSED_FOLDER
        value: /opt/render/project/src/processed
      - key: TEMP_FOLDER
        value: /opt/render/project/src/temp
    plan: free
    autoDeploy: true
    region: singapore
    healthCheckPath: /health
